# services:
#   mysql:
#     image: 'mysql:latest'
#     container_name: mysql
#     environment:
#       - 'MYSQL_DATABASE=paieapp'
#       - 'MYSQL_PASSWORD=root'
#       - 'MYSQL_ROOT_PASSWORD=root'
#       - 'MYSQL_USER=root'
#     ports:
#       - '3306:3306'
  